name: build-image

on: [push]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build image (node:10-alpine)
        uses: docker/build-push-action@v2
        with:
          file: ./node/10/Dockerfile
          push: false
      - name: Build image (node:12-alpine)
        uses: docker/build-push-action@v2
        with:
          file: ./node/12/Dockerfile
          push: false
      - name: Build image (node:14-alpine)
        uses: docker/build-push-action@v2
        with:
          file: ./node/14/Dockerfile
          push: false
      - name: Build image (node:15-alpine)
        uses: docker/build-push-action@v2
        with:
          file: ./node/15/Dockerfile
          push: false
